# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fireworks.Character'),
        ),
    ]
